// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/message.proto

package com.kuma.tools.dynamicHot.notify.register.protobuf;

public final class DataModel {
  private DataModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool pingpong = 1;</code>
     * @return The pingpong.
     */
    boolean getPingpong();

    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>int32 count = 3;</code>
     * @return The count.
     */
    int getCount();

    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pingpong_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 24: {

              count_ = input.readInt32();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.class, com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.Builder.class);
    }

    public static final int PINGPONG_FIELD_NUMBER = 1;
    private boolean pingpong_;
    /**
     * <code>bool pingpong = 1;</code>
     * @return The pingpong.
     */
    @java.lang.Override
    public boolean getPingpong() {
      return pingpong_;
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUNT_FIELD_NUMBER = 3;
    private int count_;
    /**
     * <code>int32 count = 3;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pingpong_ != false) {
        output.writeBool(1, pingpong_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      if (count_ != 0) {
        output.writeInt32(3, count_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pingpong_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, pingpong_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(key_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, count_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message)) {
        return super.equals(obj);
      }
      com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message other = (com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message) obj;

      if (getPingpong()
          != other.getPingpong()) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (getCount()
          != other.getCount()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PINGPONG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getPingpong());
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.class, com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.Builder.class);
      }

      // Construct using com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pingpong_ = false;

        key_ = "";

        count_ = 0;

        timestamp_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message getDefaultInstanceForType() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message build() {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message buildPartial() {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message result = new com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message(this);
        result.pingpong_ = pingpong_;
        result.key_ = key_;
        result.count_ = count_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message) {
          return mergeFrom((com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message other) {
        if (other == com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message.getDefaultInstance()) return this;
        if (other.getPingpong() != false) {
          setPingpong(other.getPingpong());
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean pingpong_ ;
      /**
       * <code>bool pingpong = 1;</code>
       * @return The pingpong.
       */
      @java.lang.Override
      public boolean getPingpong() {
        return pingpong_;
      }
      /**
       * <code>bool pingpong = 1;</code>
       * @param value The pingpong to set.
       * @return This builder for chaining.
       */
      public Builder setPingpong(boolean value) {
        
        pingpong_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool pingpong = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPingpong() {
        
        pingpong_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 3;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 3;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message();
    }

    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChunkInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChunkInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *START、END
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     *START、END
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string sessionId = 2;</code>
     * @return The sessionId.
     */
    java.lang.String getSessionId();
    /**
     * <code>string sessionId = 2;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>int32 chunkSize = 3;</code>
     * @return The chunkSize.
     */
    int getChunkSize();

    /**
     * <code>int32 chunkIndex = 4;</code>
     * @return The chunkIndex.
     */
    int getChunkIndex();

    /**
     * <code>repeated string data = 5;</code>
     * @return A list containing the data.
     */
    java.util.List<java.lang.String>
        getDataList();
    /**
     * <code>repeated string data = 5;</code>
     * @return The count of data.
     */
    int getDataCount();
    /**
     * <code>repeated string data = 5;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    java.lang.String getData(int index);
    /**
     * <code>repeated string data = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    com.google.protobuf.ByteString
        getDataBytes(int index);
  }
  /**
   * Protobuf type {@code ChunkInfo}
   */
  public static final class ChunkInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChunkInfo)
      ChunkInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChunkInfo.newBuilder() to construct.
    private ChunkInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChunkInfo() {
      type_ = "";
      sessionId_ = "";
      data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChunkInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChunkInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 24: {

              chunkSize_ = input.readInt32();
              break;
            }
            case 32: {

              chunkIndex_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = data_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_ChunkInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_ChunkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.class, com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     *START、END
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *START、END
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SESSIONID_FIELD_NUMBER = 2;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>string sessionId = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 2;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHUNKSIZE_FIELD_NUMBER = 3;
    private int chunkSize_;
    /**
     * <code>int32 chunkSize = 3;</code>
     * @return The chunkSize.
     */
    @java.lang.Override
    public int getChunkSize() {
      return chunkSize_;
    }

    public static final int CHUNKINDEX_FIELD_NUMBER = 4;
    private int chunkIndex_;
    /**
     * <code>int32 chunkIndex = 4;</code>
     * @return The chunkIndex.
     */
    @java.lang.Override
    public int getChunkIndex() {
      return chunkIndex_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList data_;
    /**
     * <code>repeated string data = 5;</code>
     * @return A list containing the data.
     */
    public com.google.protobuf.ProtocolStringList
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated string data = 5;</code>
     * @return The count of data.
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated string data = 5;</code>
     * @param index The index of the element to return.
     * @return The data at the given index.
     */
    public java.lang.String getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated string data = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the data at the given index.
     */
    public com.google.protobuf.ByteString
        getDataBytes(int index) {
      return data_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sessionId_);
      }
      if (chunkSize_ != 0) {
        output.writeInt32(3, chunkSize_);
      }
      if (chunkIndex_ != 0) {
        output.writeInt32(4, chunkIndex_);
      }
      for (int i = 0; i < data_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sessionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sessionId_);
      }
      if (chunkSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, chunkSize_);
      }
      if (chunkIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chunkIndex_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += computeStringSizeNoTag(data_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo)) {
        return super.equals(obj);
      }
      com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo other = (com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
      if (getChunkSize()
          != other.getChunkSize()) return false;
      if (getChunkIndex()
          != other.getChunkIndex()) return false;
      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + CHUNKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getChunkSize();
      hash = (37 * hash) + CHUNKINDEX_FIELD_NUMBER;
      hash = (53 * hash) + getChunkIndex();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChunkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChunkInfo)
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_ChunkInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_ChunkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.class, com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.Builder.class);
      }

      // Construct using com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        sessionId_ = "";

        chunkSize_ = 0;

        chunkIndex_ = 0;

        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.internal_static_ChunkInfo_descriptor;
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo getDefaultInstanceForType() {
        return com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo build() {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo buildPartial() {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo result = new com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.sessionId_ = sessionId_;
        result.chunkSize_ = chunkSize_;
        result.chunkIndex_ = chunkIndex_;
        if (((bitField0_ & 0x00000001) != 0)) {
          data_ = data_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo) {
          return mergeFrom((com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo other) {
        if (other == com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.getChunkSize() != 0) {
          setChunkSize(other.getChunkSize());
        }
        if (other.getChunkIndex() != 0) {
          setChunkIndex(other.getChunkIndex());
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *START、END
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *START、END
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *START、END
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *START、END
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *START、END
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>string sessionId = 2;</code>
       * @return The sessionId.
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sessionId = 2;</code>
       * @return The bytes for sessionId.
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 2;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 2;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private int chunkSize_ ;
      /**
       * <code>int32 chunkSize = 3;</code>
       * @return The chunkSize.
       */
      @java.lang.Override
      public int getChunkSize() {
        return chunkSize_;
      }
      /**
       * <code>int32 chunkSize = 3;</code>
       * @param value The chunkSize to set.
       * @return This builder for chaining.
       */
      public Builder setChunkSize(int value) {
        
        chunkSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkSize() {
        
        chunkSize_ = 0;
        onChanged();
        return this;
      }

      private int chunkIndex_ ;
      /**
       * <code>int32 chunkIndex = 4;</code>
       * @return The chunkIndex.
       */
      @java.lang.Override
      public int getChunkIndex() {
        return chunkIndex_;
      }
      /**
       * <code>int32 chunkIndex = 4;</code>
       * @param value The chunkIndex to set.
       * @return This builder for chaining.
       */
      public Builder setChunkIndex(int value) {
        
        chunkIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 chunkIndex = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChunkIndex() {
        
        chunkIndex_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new com.google.protobuf.LazyStringArrayList(data_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string data = 5;</code>
       * @return A list containing the data.
       */
      public com.google.protobuf.ProtocolStringList
          getDataList() {
        return data_.getUnmodifiableView();
      }
      /**
       * <code>repeated string data = 5;</code>
       * @return The count of data.
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param index The index of the element to return.
       * @return The data at the given index.
       */
      public java.lang.String getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the data at the given index.
       */
      public com.google.protobuf.ByteString
          getDataBytes(int index) {
        return data_.getByteString(index);
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param index The index to set the value at.
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param value The data to add.
       * @return This builder for chaining.
       */
      public Builder addData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param values The data to add.
       * @return This builder for chaining.
       */
      public Builder addAllData(
          java.lang.Iterable<java.lang.String> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string data = 5;</code>
       * @param value The bytes of the data to add.
       * @return This builder for chaining.
       */
      public Builder addDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChunkInfo)
    }

    // @@protoc_insertion_point(class_scope:ChunkInfo)
    private static final com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo();
    }

    public static com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChunkInfo>
        PARSER = new com.google.protobuf.AbstractParser<ChunkInfo>() {
      @java.lang.Override
      public ChunkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChunkInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChunkInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChunkInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.kuma.tools.dynamicHot.notify.register.protobuf.DataModel.ChunkInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChunkInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChunkInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037src/main/protobuf/message.proto\"J\n\007Mes" +
      "sage\022\020\n\010pingpong\030\001 \001(\010\022\013\n\003key\030\002 \001(\t\022\r\n\005c" +
      "ount\030\003 \001(\005\022\021\n\ttimestamp\030\004 \001(\003\"a\n\tChunkIn" +
      "fo\022\014\n\004type\030\001 \001(\t\022\021\n\tsessionId\030\002 \001(\t\022\021\n\tc" +
      "hunkSize\030\003 \001(\005\022\022\n\nchunkIndex\030\004 \001(\005\022\014\n\004da" +
      "ta\030\005 \003(\tB?\n2com.kuma.tools.dynamicHot.no" +
      "tify.register.protobufB\tDataModelb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Pingpong", "Key", "Count", "Timestamp", });
    internal_static_ChunkInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChunkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChunkInfo_descriptor,
        new java.lang.String[] { "Type", "SessionId", "ChunkSize", "ChunkIndex", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
